
version: "3"
services:
  nodejs-https-proxy:
    build: 
      context: .
    container_name: nodejs-https-proxy
    entrypoint: yarn start
    environment:
      TZ: America/Guayaquil
      DEFAULT_SSL_CERT: /Config/SSL/71walceli.int/service.pem
      DEFAULT_SSL_KEY: /Config/SSL/71walceli.int/service-key.pem
      REGISTERED_SERVICES_SPEC: /Config/registeredEndpoints.json
    hostname: nodejs-https-proxy
    image: node:18
    networks:
      - internal-network
    ports:
      - 443:443/tcp
    restart: unless-stopped
    volumes:
      - ./sslCerts:/Config/SSL:ro
      # All default endpoints to be available by default
      - ./registeredEndpoints.json:/Config/registeredEndpoints.json:ro
      # Any static resource should be mapped in order to be served.
      - ./cdn:/Static/cdn:ro
networks:
  # Recommended to be external as docker-compuse wuld create given network prepended folder name
  #  of where running script is.
  internal-network: 
    external: true
